import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

interface Patient {
  id: string;
  fullName: string;
  age: number;
  gender: string;
  email?: string;
  phone?: string;
  formattedPatientId: string;
  createdAt?: string;
}

interface ClinicInfo {
  name: string;
  address: string;
  phone: string;
  email: string;
  workingHours: string;
  emergencyContact: string;
  termsConditions: string;
  qrBaseUrl: string;
}

export async function generatePatientCardPDF(patient: Patient, clinic: ClinicInfo): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  // A4 portrait: 595.28 x 841.89
  const page = pdfDoc.addPage([595.28, 841.89]);
  const { width, height } = page.getSize();
  const halfHeight = height / 2;

  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const primaryColor = rgb(0.05, 0.48, 0.37); // teal
  const darkColor = rgb(0.05, 0.24, 0.18);
  const white = rgb(1, 1, 1);
  const gray = rgb(0.4, 0.4, 0.4);
  const lightGray = rgb(0.85, 0.85, 0.85);

  // ====== TOP HALF — Patient Info ======
  // Background
  page.drawRectangle({
    x: 0, y: halfHeight, width, height: halfHeight,
    color: darkColor,
  });

  // Clinic header
  page.drawText(clinic.name, {
    x: 40, y: height - 60,
    size: 22, font: fontBold, color: white,
  });
  page.drawText("Health Identity Card", {
    x: 40, y: height - 82,
    size: 10, font: fontRegular, color: rgb(0.7, 0.85, 0.8),
  });

  // Divider
  page.drawLine({
    start: { x: 40, y: height - 100 },
    end: { x: width - 40, y: height - 100 },
    thickness: 1, color: rgb(0.15, 0.35, 0.28),
  });

  // Patient details
  const labelStyle = { size: 9, font: fontRegular, color: rgb(0.6, 0.75, 0.7) };
  const valueStyle = { size: 14, font: fontBold, color: white };
  const valueSmall = { size: 12, font: fontBold, color: white };

  let y = height - 130;

  page.drawText("PATIENT NAME", { x: 40, y, ...labelStyle });
  page.drawText(patient.fullName, { x: 40, y: y - 18, ...valueStyle });

  page.drawText("PATIENT ID", { x: 350, y, ...labelStyle });
  page.drawText(patient.formattedPatientId, { x: 350, y: y - 22, size: 24, font: fontBold, color: rgb(0.3, 0.9, 0.7) });

  y -= 60;
  page.drawText("AGE", { x: 40, y, ...labelStyle });
  page.drawText(String(patient.age), { x: 40, y: y - 18, ...valueSmall });

  page.drawText("GENDER", { x: 160, y, ...labelStyle });
  page.drawText(patient.gender.charAt(0).toUpperCase() + patient.gender.slice(1), { x: 160, y: y - 18, ...valueSmall });

  page.drawText("REGISTRATION DATE", { x: 300, y, ...labelStyle });
  page.drawText(patient.createdAt, { x: 300, y: y - 18, ...valueSmall });

  // QR placeholder
  const qrY = y - 80;
  page.drawRectangle({
    x: width / 2 - 50, y: qrY, width: 100, height: 100,
    color: rgb(0.15, 0.35, 0.28),
  });
  page.drawText("QR CODE", {
    x: width / 2 - 23, y: qrY + 55,
    size: 10, font: fontBold, color: rgb(0.5, 0.7, 0.65),
  });
  const qrUrl = `${clinic.qrBaseUrl}/patient/${patient.formattedPatientId}`;
  page.drawText(qrUrl, {
    x: width / 2 - (qrUrl.length * 2.5), y: qrY + 38,
    size: 7, font: fontRegular, color: rgb(0.5, 0.7, 0.65),
  });

  // ====== BOTTOM HALF — Terms & Contact ======
  // Background
  page.drawRectangle({
    x: 0, y: 0, width, height: halfHeight,
    color: white,
  });

  // Terms header
  let ty = halfHeight - 40;
  page.drawText("Terms & Conditions", {
    x: 40, y: ty,
    size: 14, font: fontBold, color: darkColor,
  });

  ty -= 8;
  page.drawLine({
    start: { x: 40, y: ty },
    end: { x: width - 40, y: ty },
    thickness: 0.5, color: lightGray,
  });

  // Terms text
  const terms = clinic.termsConditions.split("\n");
  ty -= 20;
  for (const line of terms) {
    page.drawText(line, {
      x: 40, y: ty,
      size: 9, font: fontRegular, color: gray,
    });
    ty -= 16;
  }

  // Contact section
  ty -= 20;
  page.drawLine({
    start: { x: 40, y: ty + 10 },
    end: { x: width - 40, y: ty + 10 },
    thickness: 0.5, color: lightGray,
  });

  ty -= 5;
  const contactLines = [
    `Address: ${clinic.address}`,
    `Phone: ${clinic.phone}  |  Email: ${clinic.email}`,
    `Working Hours: ${clinic.workingHours}`,
    `Emergency Contact: ${clinic.emergencyContact}`,
  ];

  for (const line of contactLines) {
    page.drawText(line, {
      x: 40, y: ty,
      size: 9, font: fontRegular, color: gray,
    });
    ty -= 16;
  }

  // Footer
  page.drawText(`Generated by ${clinic.name} — ClinicToken CMS Pro`, {
    x: 40, y: 30,
    size: 7, font: fontRegular, color: lightGray,
  });

  return pdfDoc.save();
}
