import jsPDF from 'jspdf'

export const generatePatientCardPDF = async (patient: any, clinic: any) => {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    })

    const pageW = 210
    const cardW = 90
    const cardH = 55
    const x = (pageW - cardW) / 2
    const y = 20

    // Card background top half (dark)
    doc.setFillColor(30, 41, 59)
    doc.roundedRect(x, y, cardW, cardH / 2, 3, 3, 'F')

    // Card background bottom half (white)
    doc.setFillColor(255, 255, 255)
    doc.roundedRect(x, y + cardH / 2, cardW, cardH / 2, 3, 3, 'F')

    // Card border
    doc.setDrawColor(14, 165, 233)
    doc.setLineWidth(0.5)
    doc.roundedRect(x, y, cardW, cardH, 3, 3, 'S')

    // Clinic name
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text(clinic?.clinic_name || 'Clinic', x + cardW / 2, y + 8, { align: 'center' })

    // Patient ID large
    doc.setFontSize(18)
    doc.setTextColor(14, 165, 233)
    doc.text(patient?.formatted_patient_id || 'M-001', x + cardW / 2, y + 18, { align: 'center' })

    // Patient name
    doc.setFontSize(9)
    doc.setTextColor(255, 255, 255)
    doc.setFont('helvetica', 'normal')
    doc.text(patient?.full_name || '', x + cardW / 2, y + 24, { align: 'center' })

    // Age and gender
    doc.setFontSize(8)
    doc.text(
      `Age: ${patient?.age || ''}  |  Gender: ${patient?.gender || ''}`,
      x + cardW / 2, y + 29, { align: 'center' }
    )

    // Bottom white section
    doc.setTextColor(30, 41, 59)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')

    const terms = clinic?.terms_conditions || 'Patient ID card issued by clinic.'
    const lines = doc.splitTextToSize(terms, cardW - 6)
    doc.text(lines.slice(0, 4), x + 3, y + cardH / 2 + 5)

    // Contact info
    doc.setFontSize(6.5)
    doc.text(clinic?.contact_phone || '', x + 3, y + cardH - 5)
    doc.text(clinic?.contact_email || '', x + cardW / 2, y + cardH - 5, { align: 'center' })

    // Footer
    doc.setFontSize(6)
    doc.setTextColor(100, 100, 100)
    doc.text(
      `Generated by ${clinic?.clinic_name || 'ClinicToken CMS'}`,
      pageW / 2, y + cardH + 8, { align: 'center' }
    )

    // Save
    const filename = `PatientCard-${patient?.formatted_patient_id || 'card'}-${clinic?.short_name || 'clinic'}.pdf`
    doc.save(filename)
    return true

  } catch (err) {
    console.error('PDF generation error:', err)
    throw new Error('Failed to generate PDF')
  }
}
